dataset:
  root_dir: "./data/autoshot"
  frame_root: "./data/autoshot_frames"
  label_root: "/data/autoshot"
training:
  batch_size: 256
  epochs: 50
  learning_rate: 1e-4
  pos_weight: 5.0
  distill_weight: 0.5
model:
  threshold: 0.4
  device: "cuda"
output:
  save_path: "./checkpoints"
